export const CONFIG = {
  BANK_WALLET: import.meta.env.VITE_BANK_WALLET,
  DEV_WALLET: import.meta.env.VITE_DEV_WALLET,
  ADSGRAM_BLOCK_ID: import.meta.env.VITE_ADSGRAM_BLOCK_ID || '45638',
  DEV_SHARE: 0.20,
  DEV_SHARE_ADS: 0.50,
  TOKENS_PER_AD: 20,
  POINTS_PER_AD: 10,
  GRAM_TO_TOKENS: 10000,
  TON_TO_TOKENS: 10000,
  MIN_WITHDRAWAL_TOKENS: 50000,
  MIN_WITHDRAWAL_GRAM: 5,
}
